source /etc/bash_completion.d/git-prompt
alias ls='ls --color=auto'

# Avoid duplicates
export HISTCONTROL=ignoreboth:erasedups
export HISTFILESIZE=-1
export HISTSIZE=-1
export HISTTIMEFORMAT="[%h %d %H:%M:%S] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend
# But also just immediately send every command, helpful for tmux
export PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

source ~/dotfiles/bash/bash_colors
export GIT_PS1_SHOWDIRTYSTATE="true"
export GIT_PS1_SHOWSTASHSTATE="true"
export GIT_PS1_SHOWUNTRACKEDFILES="true"
export GIT_PS1_SHOWUPSTREAM="auto"

if [ "$SSH_CONNECTION" ] || [ "$SSH_CLIENT" ] || [ "$SSH_TTY" ]; then
        PS1='\u@\h:\W/ $(__git_ps1 "\[$txtcyn\](%s)")\[$txtrst\]\$ '
else
        PS1='\W/ $(__git_ps1 "\[$txtcyn\](%s)")\[$txtrst\]\$ '
fi

bind 'set completion-ignore-case on'
export EDITOR=vim
export CLICOLOR=1
export LSCOLORS=exfxbxdxcxegedabagacad
export TERM=xterm-256color

# This fn sets the title of the iterm tab
# bash$ title my-little-pony
function title {
    echo -ne "\033]0;"$*"\007"
}

alias gf='fg'
